--- 
abstract: Wrap system command binaries the Moose way
author: 
  - Eden Cardim <edencardim@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Role-Cmd
no_index: 
  directory: 
    - inc
    - t
requires: 
  IPC::Cmd: 0
  Moose: 0.24
version: 0.01
